### ISSUE TITLE
`stddev( [47] )` results in error

### ISSUE THREAD

**Issue by Prokopp** [camunda-community-hub/feel-scala-playground#54]
According to DMN FEEL Handbook `stddev( [47] )` should result in `null` but results in an error: 
`failed to evaluate expression 'stddev( [47] )' : java.lang.ArithmeticException: Division undefined`

**Comment by saig0** [comment]
@Prokopp please report issues of the FEEL engine in the feel-scala project [here](https://github.com/camunda/feel-scala/issues). This repository is only about the FEEL playground and its API.

For this concrete problem, good catch. :+1: Please create an issue.
