### ISSUE TITLE
Unicode and substring()

### ISSUE THREAD

**Issue by Prokopp** [camunda-community-hub/feel-scala-playground#56]
`substring( "🐎ab", 2 )` returns `"\udc0eab"` not `"ab"`

`substring( "\U01F40Eab", 2 )` returns `"U01F40Eab"`

See DMN FEEL Handbook for example.

**Comment by saig0** [comment]
@Prokopp please report issues of the FEEL engine in the feel-scala project [here](https://github.com/camunda/feel-scala/issues). This repository is only about the FEEL playground and its API. 

For this concrete problem, we already have an issue: https://github.com/camunda/feel-scala/issues/558
