### ISSUE TITLE
distinct values() does not correctly detect duplicate objects in a list

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/feel-scala-playground#66]
[test case](https://camunda.github.io/feel-scala/docs/playground/?expression=ZGlzdGluY3QgdmFsdWVzKAogIGZsYXR0ZW4oCiAgICBmb3IgcmVxdWVzdCBpbiBnZXQgZW50cmllcyhleHBlcmltZW50UmVxdWVzdHMpLnZhbHVlIHJldHVybiAKICAgICAgZm9yIGFzc2F5IGluIHJlcXVlc3Quc2NyZWVuaW5nQXNzYXlzCiAgICAgICAgcmV0dXJuIHthc3NheTogYXNzYXksIGNvbXBvdW5kczogcmVxdWVzdC5jb21wb3VuZHN9CiAgKQopCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA%3D%3D&context=eyJleHBlcmltZW50UmVxdWVzdHMiOnsKCSIyNiI6IHsKCQkiZ2FsSURzIjogIkcyMDIyOTkzLTFcbkcyMDIxMzg5LTFcbkcyMDIyNDc1LTFcbkcyMDIyNjQwLTFcbkcyMDIyNzAwLTFcbkcyMDIyNzQ4LTFcbkcyMDIyOTU4LTFcbkcyMDIyOTg2LTFcbkcyMDIzMDcwLTFcbkcyMTgwNzMzLTEiLAoJCSJjb21wb3VuZHMiOiBbCgkJCXsKCQkJCSJjb21wb3VuZCI6ICJHMjAyMTM4OS0xIiwKCQkJCSJjb25jZW50cmF0aW9uIjogMTAKCQkJfQoJCV0sCgkJInByb2plY3RDb2RlIjogIkdUOTU1MSIsCgkJImNvbXBvdW5kTGlzdCI6IFsKCQkJIkcyMDIyOTkzLTEiLAoJCQkiRzIwMjEzODktMSIsCgkJCSJHMjAyMjQ3NS0xIiwKCQkJIkcyMDIyNjQwLTEiLAoJCQkiRzIwMjI3MDAtMSIsCgkJCSJHMjAyMjc0OC0xIiwKCQkJIkcyMDIyOTU4LTEiLAoJCQkiRzIwMjI5ODYtMSIsCgkJCSJHMjAyMzA3MC0xIiwKCQkJIkcyMTgwNzMzLTEiCgkJXSwKCQkibXlTZXJ2aWNlUmVzdWx0IjogIkhlbGxvIGZyb20gemJjdGwhIiwKCQkic2NyZWVuaW5nQXNzYXlzIjogWwoJCQkiU0lLMV8yXzNfQURQZ2xvIiwiRmFsa28ncyBBc3NheSIKCQldLAoJCSJjb25jZW50cmF0aW9uVW5pdCI6ICJtTSIsCgkJImNvbmNlbnRyYXRpb25WYWx1ZSI6IDEwCgl9LAoJIjI3IjogewoJCSJnYWxJRHMiOiAiRzIwMjI5OTMtMVxuRzIwMjEzODktMVxuRzIwMjI0NzUtMVxuRzIwMjI2NDAtMVxuRzIwMjI3MDAtMVxuRzIwMjI3NDgtMVxuRzIwMjI5NTgtMVxuRzIwMjI5ODYtMVxuRzIwMjMwNzAtMVxuRzIxODA3MzMtMSIsCgkJImNvbXBvdW5kcyI6IFsKCQkJewoJCQkJImNvbXBvdW5kIjogIkcyMDIxMzg5LTEiLAoJCQkJImNvbmNlbnRyYXRpb24iOiAxMAoJCQl9CgkJXSwKCQkicHJvamVjdENvZGUiOiAiR1Q5NTUxIiwKCQkiY29tcG91bmRMaXN0IjogWwoJCQkiRzIwMjI5OTMtMSIsCgkJCSJHMjAyMTM4OS0xIiwKCQkJIkcyMDIyNDc1LTEiLAoJCQkiRzIwMjI2NDAtMSIsCgkJCSJHMjAyMjcwMC0xIiwKCQkJIkcyMDIyNzQ4LTEiLAoJCQkiRzIwMjI5NTgtMSIsCgkJCSJHMjAyMjk4Ni0xIiwKCQkJIkcyMDIzMDcwLTEiLAoJCQkiRzIxODA3MzMtMSIKCQldLAoJCSJteVNlcnZpY2VSZXN1bHQiOiAiSGVsbG8gZnJvbSB6YmN0bCEiLAoJCSJzY3JlZW5pbmdBc3NheXMiOiBbCgkJCSJTSUsxXzJfM19BRFBnbG8iCgkJXSwKCQkiY29uY2VudHJhdGlvblVuaXQiOiAibU0iLAoJCSJjb25jZW50cmF0aW9uVmFsdWUiOiAxMAoJfQp9fQ%3D%3D&expression-type=expression)

It works correctly in the [JavaScript FEEL Playground](https://nikku.github.io/feel-playground/?e=%7E3YCAkICGgYCAgICAgICymspOoKN5UzD9spBYgDUZmKGtgYRGSzFOiEiyvTLIOuo2sNaKoK7gFz%2FjLUzPRPxAxqxV5Ngli06MDDPFPuvLnyBbfRvw8CC9%2BD%2BWVG7P3OxwBj9ILy1lM9c2FX3VW92kDfh7nb3kQui87GxJuxqdsvh67S%2F%2FL4iqZlsTSNN6DgZFIfL27R6de5l83C3A&c=%7E3YCAkIBbhICAgICAgIC9CAgnQ2xJ3ySrKETG2IU7sdfFcZx4%2BMdyb9h6qQxAMHe6u5xtlU%2FHVcVXblaTULL8ayvtaPFkzBCaCgs%2FQWC38OUZJT00dTWasCyYJ4cSCi8YMKDPnnB%2FA%2BQ%2FdUlehXugw%2F3p7lTN48%2BI8PL0w31wC4xMPG47UCHuAb4YHhVIrzLnpAUB%2B70Zgo92H%2BCd7bsshOOdXdgCJ9OwlkB4iFO0aA41rBLWv4L11vhC7%2BNjeGkyaluotVBrueZ6SHjOF9lDFlFledEgGZdgSRHbMm1ySOofAe66dVmggtZUMicARdZOkj%2FA%2FfQuXsBLObyhWZf3wYpkh3isrqQ%2Fq6PXfeKI%2F2qOaEwQYSJFmB03WwB5quZh2SQXLe7k%2FqlNLDbnPwfbvzZdT2wNVG9HfeQddRd1dVr4cwJVs1ic4kT6WXuMkuQ%3D&t=expression&st=false) from @nikku

**Comment by falko** [comment]
This is [not tested in much detail in the DMN TCK](https://github.com/search?q=repo%3Admn-
tck%2Ftck+distinct+language%3AXML&type=code)

**Comment by falko** [comment]
This is likely an issue with the upstream FEEL-Scala library and the playground just surfaced it.

**Comment by saig0** [comment]
This is a known issue in the FEEL engine: https://github.com/camunda/feel-scala/issues/771

I'm closing this issue in favor of the linked issue from the FEEL engine.
